export const routeMenu = [
  {
    id: "1228549913133977602",
    parentId: "0",
    sort: "1",
    name: "Project overview",
    Code: "",
    Type: "1",
    TypeName: "普通菜单",
    Url: "/ProjectOverview",
    RouterName: "ProjectOverview",
    PermIcon: "shujugl",
    menuLevel: "top",
    dividerAfter: true,
  },
  {
    id: "2000000000000000001",
    parentId: "0",
    sort: "2",
    name: "Select a project first",
    Code: "",
    Type: "1",
    TypeName: "普通菜单",
    Url: "",
    RouterName: "XxxProject",
    PermIcon: "shujugl",
    menuLevel: "group",
    requireProject: true,
    children: [
      {
        id: "1428549913133977602",
        parentId: "2000000000000000001",
        sort: "0",
        name: "Request master",
        Code: "",
        Type: "1",
        TypeName: "普通菜单",
        Url: "/RequestMaster",
        RouterName: "RequestMaster",
        PermIcon: "shujugl",
        menuLevel: "leaf",
        showStatus: true,
        requireProject: true,
      },
      {
        id: "1028549913133977602",
        parentId: "2000000000000000001",
        sort: "1",
        name: "Control table",
        Code: "",
        Type: "1",
        TypeName: "普通菜单",
        Url: "/ControlTesting",
        RouterName: "ControlTesting",
        PermIcon: "shujugl",
        menuLevel: "leaf",
        showStatus: true,
        requireProject: true,
      },
      {
        id: "1038549913133977602",
        parentId: "2000000000000000001",
        sort: "2",
        name: "Gap analysis",
        Code: "",
        Type: "1",
        TypeName: "普通菜单",
        Url: "/GapAnalysis",
        RouterName: "GapAnalysis",
        PermIcon: "shujugl",
        menuLevel: "leaf",
        showStatus: true,
        requireProject: true,
      },
      {
        id: "1228549913133977601",
        parentId: "2000000000000000001",
        sort: "3",
        name: "Passing scores",
        Code: "",
        Type: "1",
        TypeName: "普通菜单",
        Url: "/PassingScores",
        RouterName: "PassingScores",
        PermIcon: "shujugl",
        menuLevel: "leaf",
        showStatus: true,
        requireProject: true,
      },
      {
        id: "1048549913133977602",
        parentId: "2000000000000000001",
        sort: "4",
        name: "Access management",
        Code: "",
        Type: "1",
        TypeName: "普通菜单",
        Url: "/ProjectSettings",
        RouterName: "ProjectSettings",
        PermIcon: "shujugl",
        menuLevel: "leaf",
        showStatus: true,
        requireProject: true,
      },
      {
        id: "1428549913133977601",
        parentId: "2000000000000000001",
        sort: "5",
        name: "Risk table",
        Code: "",
        Type: "1",
        TypeName: "普通菜单",
        Url: "/longblade",
        RouterName: "RcmFinal",
        PermIcon: "shujugl",
        menuLevel: "leaf",
        showStatus: true,
        requireProject: true,
      },
      {
        id: "1128549913133977602",
        parentId: "2000000000000000001",
        sort: "6",
        name: "Operation log",
        Code: "",
        Type: "1",
        TypeName: "普通菜单",
        Url: "/OperationLog",
        RouterName: "OperationLog",
        PermIcon: "shujugl",
        menuLevel: "leaf",
        showStatus: true,
        requireProject: true,
      },
    ],
  },
  {
    id: "1528549913133977602",
    parentId: "0",
    sort: "3",
    name: "System Users",
    Code: "",
    Type: "1",
    TypeName: "普通菜单",
    Url: "/SystemUsers",
    RouterName: "SystemUsers",
    PermIcon: "shujugl",
    menuLevel: "top",
    requireSystemRole: "COMP_ADMIN",
    dividerBefore: true,
  },
];
